"""
This file is used for fast operations on localization. It consists of a list of all the languages on its own language,
language_codes and translation of all the text in the app into some language.
"""

langs = [
    "afrikaans", "shqiptar", "አማርኛ", "عربى", "հայերեն", "Azərbaycan", "basque", "беларускі", "বাংলা",
    "bosanski", "български", "català", "cebuano", "Chichewa", "简体中文", "中國傳統的", "Corsu", "Hrvatski",
    "čeština", "dansk", "Nederlands", "english", "esperanto", "eesti", "filipino", "Suomalainen", "français",
    "Frysk", "galician", "ქართული", "Deutsche", "Ελληνικά", "ગુજરાતી", "ayisyen kreyòl", "Hausa",
    "Ōlelo Hawaiʻi", "עִברִית", "עִברִית", "हिंदी", "hmong", "Magyar", "icelandic", "igbo", "bahasa Indonesia",
    "Gaeilge", "italiano", "日本語", "javanese", "ಕನ್ನಡ", "Қазақ", "ខ្មែរ", "한국어", "Kurdish (Kurmanji)",
    "Кыргызча", "ລາວ", "Latine", "Latvijas", "Lietuvos", "Lëtzebuergesch", "македонски", "Malagasy", "malay",
    "മലയാളം", "maltese", "maori", "मराठी", "монгол", "မြန်မာ (ဗမာ)", "नेपाली", "norsk", "ଓଡ଼ିଆ", "پښتو", "فارسی",
    "Polskie", "português", "ਪੰਜਾਬੀ", "Română", "русский", "Samoa", "Gàidhlig", "Српски", "Sesotho", "shona",
    "سنڌي", "සිංහල", "slovenský", "Slovenščina", "somali", "Español", "tembang sunda", "swahili", "svenska",
    "тоҷик", "தமிழ்", "తెలుగు", "ไทย", "Türk", "український", "اردو", "ئۇيغۇر", "uzbek", "Tiếng Việt",
    "Cymraeg", "isiXhosa", "ייִדיש", "Yoruba", "zulu"
]

codes = [
    "af", "sq", "am", "ar", "hy", "az", "eu", "be", "bn", "bs", "bg", "ca", "ceb", "ny", "zh-cn", "zh-tw", "co", "hr",
    "cs", "da", "nl", "en", "eo", "et", "tl", "fi", "fr", "fy", "gl", "ka", "de", "el", "gu", "ht", "ha", "haw", "iw",
    "he", "hi", "hmn", "hu", "is", "ig", "id", "ga", "it", "ja", "jw", "kn", "kk", "km", "ko", "ku", "ky", "lo", "la",
    "lv", "lt", "lb", "mk", "mg", "ms", "ml", "mt", "mi", "mr", "mn", "my", "ne", "no", "or", "ps", "fa", "pl", "pt",
    "pa", "ro", "ru", "sm", "gd", "sr", "st", "sn", "sd", "si", "sk", "sl", "so", "es", "su", "sw", "sv", "tg", "ta",
    "te", "th", "tr", "uk", "ur", "ug", "uz", "vi", "cy", "xh", "yi", "yo", "zu"
]

ans = {
    "af": ["begin", "instellings", "selfmoord", "terug"],
    "sq": ["fillim", "Cilësimet", "vetëvrasje", "prapa"],
    "am": ["መጀመሪያ", "ቅንብሮች", "ራስን መግደል", "ወደኋላ"],
    "ar": ["بداية", "إعدادات", "انتحار", "عودة"],
    "hy": ["սկիզբ", "Կարգավորումներ", "ինքնասպանություն", "Վերադառնալ"],
    "az": ["Başlamaq", "Settings", "intihar", "geri"],
    "eu": ["start", "ezarpenak", "Suicide", "Back"],
    "be": ["пачатак", "налады", "самазабойца", "назад"],
    "bn": ["শুরু", "সেটিংস", "আত্মহত্যা", "পেছনে"],
    "bs": ["start", "Postavke", "samoubistvo", "natrag"],
    "bg": ["начало", "Настройки", "самоубийство", "обратно"],
    "ca": ["Començar", "ajustos", "suïcidi", "esquena"],
    "ceb": ["Start", "setting", "paghikog", "balik"],
    "ny": ["Start", "Zikhazikiko", "kudzipha", "Back"],
    "zh-cn": ["开始", "设置", "自杀", "后退"],
    "zh-tw": ["開始", "設置", "自殺", "後退"],
    "co": ["Start", "Settings", "Mariposa", "Torna"],
    "hr": ["Početak", "postavke", "samoubistvo", "leđa"],
    "cs": ["Start", "Nastavení", "Sebevražda", "Zadní"],
    "da": ["Start", "Indstillinger", "Selvmord", "Tilbage"],
    "nl": ["Begin", "instellingen", "Zelfmoord", "Terug"],
    "en": ["Start", "Settings", "Suicide", "Back"],
    "eo": ["komenco", "Agordoj", "memmortigo", "reen"],
    "et": ["algus", "seaded", "enesetapp", "tagasi"],
    "tl": ["simula", "Mga Setting", "pagpapakamatay", "likod"],
    "fi": ["alkaa", "asetukset", "Itsemurha", "Takaisin"],
    "fr": ["Démarrer", "Paramètres", "Suicide", "Dos"],
    "fy": ["Start", "ynstellings", "Selsmoard", "Rêch"],
    "gl": ["comezo", "configuración", "suicidio", "de volta"],
    "ka": ["დაწყება", "პარამეტრები", "Suicide", "უკან"],
    "de": ["Start", "die Einstellungen", "Selbstmord", "Zurück"],
    "el": ["Αρχή", "Ρυθμίσεις", "Αυτοκτονία", "Πίσω"],
    "gu": ["શરૂઆત", "સેટિંગ્સ", "આત્મઘાતી", "પાછા"],
    "ht": ["Kòmanse", "anviwònman", "swisid", "Retounen"],
    "ha": ["Fara", "Saituna", "Kashe Kanta", "baya"],
    "haw": ["Ka hoʻomaka '", "palapala koho", "he pepehi anaʻia iā iho", "Back"],
    "iw": ["הַתחָלָה", "הגדרות", "הִתאַבְּדוּת", "חזור"],
    "he": ["הַתחָלָה", "הגדרות", "הִתאַבְּדוּת", "חזור"],
    "hi": ["शुरू", "समायोजन", "आत्मघाती", "वापस"],
    "hmn": ["Start", "chaw", "yus tua yus", "Rov qab"],
    "hu": ["Rajt", "Beállítások", "Öngyilkosság", "Vissza"],
    "is": ["Start", "Stillingar", "sjálfsvíg", "Back"],
    "ig": ["Malite", "Settings", "igbu onwe", "Back"],
    "id": ["Mulailah", "pengaturan", "Bunuh diri", "Kembali"],
    "ga": ["Tosaigh", "Socruithe", "Féinmharú", "Ar ais"],
    "it": ["Inizio", "impostazioni", "Suicidio", "Indietro"],
    "ja": ["開始", "設定", "自殺", "バック"],
    "jw": ["Mulai", "Setelan", "lampus", "Back"],
    "kn": ["ಪ್ರಾರಂಭಿಸಿ", "ಸಂಯೋಜನೆಗಳು", "ಸುಸೈಡ್", "ಬ್ಯಾಕ್"],
    "kk": ["бастау", "Параметрлер", "Суицид", "артқа"],
    "km": ["ចាប់ផ្តើម", "ការកំណត់", "ការធ្វើអត្តឃាត", "ត្រលប់ក្រោយ"],
    "ko": ["스타트", "설정", "자살", "뒤"],
    "ku": ["Destpêkirin", "Mîhengên", "Xwekûştinî", "Paş"],
    "ky": ["баштоо", "Орнотуулар", "өзүн өзү өлтүрүү", "кайра"],
    "lo": ["ເລີ່ມຕົ້ນ", "ການຕັ້ງຄ່າ", "suicide", "ກັບຄືນໄປບ່ອນ"],
    "la": ["initium", "Optiones", "mortem", "Back"],
    "lv": ["Sākt", "Iestatījumi", "pašnāvība", "atpakaļ"],
    "lt": ["pradžia", "Nustatymai", "savižudybė", "atgal"],
    "lb": ["Start", "Astellunge", "ëmbruecht", "Back"],
    "mk": ["почеток", "Подесувања", "самоубиството", "назад"],
    "mg": ["fanombohana", "Fikirana", "Mamono Tena", "indray"],
    "ms": ["Start", "tetapan", "bunuh diri", "Kembali"],
    "ml": ["തുടക്കം", "ക്രമീകരണങ്ങൾ", "ആത്മഹത്യ", "തിരികെ"],
    "mt": ["bidu", "settings", "suwiċidju", "lura"],
    "mi": ["Tīmata", "tautuhinga", "whakamomori", "Hoki"],
    "mr": ["प्रारंभ", "सेटिंग्ज", "आत्महत्या", "मागे"],
    "mn": ["Start", "Тохиргоо", "амиа хорлох", "Буцах Give"],
    "my": ["စတင်", "Settings များ", "မိမိကိုယ်မိမိသတ်သေခြင်း", "ပြန်."],
    "ne": ["सुरु", "सेटिङहरू", "आत्महत्या", "फिर्ता"],
    "no": ["Start", "innstillinger", "Selvmord", "Tilbake"],
    "or": ["ଆରମ୍ଭ", "ସେଟିଂସମୂହ", "ଆତ୍ମହତ୍ଯା", "ପିଠି"],
    "ps": ["د پیل", "امستنې", "ځانمرګي", "Back"],
    "fa": ["شروع", "تنظیمات", "خودکشی کردن", "بازگشت"],
    "pl": ["Początek", "Ustawienia", "Samobójstwo", "Z powrotem"],
    "pt": ["Começar", "Definições", "Suicídio", "Voltar"],
    "pa": ["ਸ਼ੁਰੂ", "ਸੈਟਿੰਗ", "ਖੁਦਕੁਸ਼ੀ", "ਵਾਪਸ"],
    "ro": ["start", "Setări", "Sinucidere", "Înapoi"],
    "ru": ["Начинать", "Настройки", "самоубийца", "Назад"],
    "sm": ["āmata", "tulaga", "tōaʻi", "tua"],
    "gd": ["Start", "Roghainnean", "Suicide", "Back"],
    "sr": ["Почетак", "Подешавања", "самоубиство", "Назад"],
    "st": ["Qala", "Litlhophiso", "ho ipolaea", "morao"],
    "sn": ["kutanga", "Settings", "kuzvisungirira", "shure"],
    "sd": ["شروع", "جوڙ", "آپگهات", "واپس"],
    "si": ["ආරම්භයක්", "සැකසුම්", "මරාගෙන මැරෙන", "ආපසු"],
    "sk": ["štart", "nastavenie", "samovražda", "späť"],
    "sl": ["Začetek", "Nastavitve", "samomor", "Nazaj"],
    "so": ["Start", "Settings", "ismiidaamin ah", "Back"],
    "es": ["Comienzo", "Ajustes", "Suicidio", "atrás"],
    "su": ["ngamimitian", "setélan", "maehan maneh", "balik deui"],
    "sw": ["Start", "mipangilio", "Suicide", "Back"],
    "sv": ["Start", "inställningar", "Självmord", "Tillbaka"],
    "tg": ["Оғоз", "Танзимот", "худкушӣ", "Бозгашт"],
    "ta": ["தொடக்கம்", "அமைப்புகள்", "தற்கொலை", "மீண்டும்"],
    "te": ["ప్రారంభం", "సెట్టింగులు", "ఆత్మహత్య", "తిరిగి"],
    "th": ["เริ่มต้น", "การตั้งค่า", "การฆ่าตัวตาย", "กลับ"],
    "tr": ["Başlat", "Ayarlar", "İntihar", "Geri"],
    "uk": ["початок", "настройки", "самогубець", "назад"],
    "ur": ["شروع کریں", "ترتیبات", "خودکش", "پیچھے"],
    "ug": ["жүргүзмәк", "تەڭشەكلىرى", "өз-өзини өлтүрүш", "قايتىپ"],
    "uz": ["boshlanish", "Sozlamalar", "o'zini o'zi o'ldirish", "orqaga"],
    "vi": ["Khởi đầu", "Cài đặt", "tự vận", "Trở lại"],
    "cy": ["Dechrau", "gosodiadau", "hunanladdiad", "Yn ôl"],
    "xh": ["Qala", "izicwangciso", "ukuzibulala", "buyela umva"],
    "yi": ["אָנהייב", "סעטטינגס", "זעלבסטמאָרד", "צוריק"],
    "yo": ["Bẹrẹ", "Ètò", "ara", "Back"],
    "zu": ["Qala", "Amasethingi", "Ukuzibulala", "Emuva"],
}
